#!/usr/bin/env perl
use Mojolicious::Lite;
use YAML::Tiny;

plugin('FormFields');

my $yaml = YAML::Tiny->new;

get '/' => sub {
  my $c = shift;
  my $data = $yaml->read('nginx.yaml');
  $data = $data->[0];
  $c->render(template => 'index', yaml => $data);
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';

<%= field($yaml->{daemon}->{key})->label('daemon') %>
<%= field($yaml->{daemon}->{key})->input %> <br />
@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
